export const TOKEN_REQUEST = 'USERS_TOKEN_REQUEST';
export const TOKEN_RECEIVED = 'USERS_TOKEN_RECEIVED';
export const TOKEN_FAILURE = 'USERS_TOKEN_FAILURE';
export const FAILED_AUTH = 'FAILED_AUTH';
